In [1]:
import torch

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
a = torch.randn(1,3)

In [4]:
a

tensor([[-2.2096,  0.9384,  1.8276]])

In [6]:
a.device

device(type='cpu')

In [17]:
import pandas as pd
classes_all = pd.read_csv('lists/ntu_60_labels.csv').values

In [19]:
len(classes_all)

60

In [18]:
label = torch.tensor([1,2], dtype = torch.long).to('cuda:1')

In [15]:
label

tensor([1, 2], device='cuda:1')

In [17]:
for idx in label:
    print(idx)

tensor(1, device='cuda:1')
tensor(2, device='cuda:1')


In [1]:
import torch
idx = torch.tensor([1,2,1], dtype=torch.long)

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
idx = idx.view(-1, 1)

In [5]:
idx.shape

torch.Size([3, 1])

In [9]:
pos_idx = torch.eq(idx, idx.t()).float()

In [10]:
pos_idx/pos_idx.sum(1, keepdim=True)

tensor([[0.5000, 0.0000, 0.5000],
        [0.0000, 1.0000, 0.0000],
        [0.5000, 0.0000, 0.5000]])

In [11]:
import torch.nn.functional as F

In [12]:
a = torch.randn([2,3,2])

In [13]:
a

tensor([[[ 0.0038, -1.1968],
         [-0.6987,  1.9945],
         [-0.9686, -0.7478]],

        [[-1.6464,  0.6354],
         [-0.0933,  0.6522],
         [ 0.0112, -0.6693]]])

In [15]:
F.softmax(a, dim=2).mean(dim=1)

tensor([[0.4257, 0.5743],
        [0.3594, 0.6406]])

In [16]:
a.mean(dim=1)

tensor([[-0.5545,  0.0166],
        [-0.5761,  0.2061]])

In [20]:
a = dict()

In [21]:
b = {'loss':1, 'acc':2}

In [22]:
b

{'loss': 1, 'acc': 2}

In [23]:
a.update(b)

In [24]:
a

{'loss': 1, 'acc': 2}

In [1]:
import torch

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [8]:
a = torch.tensor([13, 14, 13, 13, 13], dtype = torch.long)

In [9]:
torch.allclose(a, a[0])

False

In [10]:
a.shape

torch.Size([5])

In [1]:
import torch

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = torch.randn(3, 3)

In [3]:
a

tensor([[ 2.3450, -0.7396, -0.4845],
        [ 1.3909, -1.2365, -0.3889],
        [-0.2217, -1.1217,  0.7093]])

In [4]:
label = torch.tensor([1, 2, 1], dtype = torch.long)

In [5]:
label = label.view(-1, 1)

In [6]:
torch.eq(label, label.t())

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [8]:
a.masked_fill(torch.eq(label, label.t()), 0)

tensor([[ 0.0000, -0.7396,  0.0000],
        [ 1.3909,  0.0000, -0.3889],
        [ 0.0000, -1.1217,  0.0000]])

In [1]:
a = [0, 1, 2, 3]

In [4]:
a[1:] = [1, 1, 1]

In [5]:
a

[0, 1, 1, 1]

In [1]:
import torch

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
sim_targets = torch.tensor([[1.0, 0],[0.5,0.5]], dtype = torch.float32)
sim_i2t = torch.randn((2,2))

In [3]:
sim_i2t

tensor([[ 1.0559, -1.2462],
        [ 0.0509,  0.9976]])

In [4]:
import torch.nn.functional as F 

In [9]:
F.log_softmax(sim_i2t, dim=1)*sim_targets

tensor([[-0.0953, -0.0000],
        [-0.6373, -0.1639]])

In [10]:
-torch.sum(F.log_softmax(sim_i2t, dim=1)*sim_targets, dim=1)

tensor([0.0953, 0.8012])

In [11]:
-torch.sum(F.log_softmax(sim_i2t, dim=1)*sim_targets, dim=1).mean()

tensor(0.4483)

In [1]:
import torch
a = torch.tensor(
    [
        [[1.,1],
        [2,2],
        [1,1]],
        [[2,2],
        [4,4],
        [3,3]],
    ]
)

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a.shape

torch.Size([2, 3, 2])

In [3]:
b = torch.tensor(
    [[1.,1],
    [2,2]]
)

In [4]:
b.shape

torch.Size([2, 2])

In [5]:
c = torch.sum(a*b.unsqueeze(1), dim=-1)

In [6]:
c

tensor([[ 2.,  4.,  2.],
        [ 8., 16., 12.]])

In [7]:
torch.einsum('btc,bc->bt', a, b)

tensor([[ 2.,  4.,  2.],
        [ 8., 16., 12.]])

In [8]:
import torch.nn.functional as F

In [9]:
d = F.softmax(c, dim=-1)

In [10]:
d

tensor([[1.0651e-01, 7.8699e-01, 1.0651e-01],
        [3.2932e-04, 9.8169e-01, 1.7980e-02]])

In [11]:
d.unsqueeze(2)*a

tensor([[[1.0651e-01, 1.0651e-01],
         [1.5740e+00, 1.5740e+00],
         [1.0651e-01, 1.0651e-01]],

        [[6.5864e-04, 6.5864e-04],
         [3.9268e+00, 3.9268e+00],
         [5.3941e-02, 5.3941e-02]]])

In [12]:
torch.sum(d.unsqueeze(2)*a, dim=1)

tensor([[1.7870, 1.7870],
        [3.9814, 3.9814]])

In [13]:
torch.einsum('bt,btc->bc', d, a)

tensor([[1.7870, 1.7870],
        [3.9814, 3.9814]])

In [4]:
import torch
T = 3
C = 5
L = 4
a = torch.randn((2,T,C), dtype = torch.float32)
b = torch.randn((L, C), dtype = torch.float32)

In [5]:
a.shape

torch.Size([2, 3, 5])

In [6]:
b.shape

torch.Size([4, 5])

In [17]:
c = torch.einsum('btc,lc->blt', a,b)

In [18]:
c[0,0,:]

tensor([-0.1188,  1.6346, -1.9411])

In [20]:
torch.sum(a[0,:,:]*(b[0,:].unsqueeze(0)), dim=-1)

tensor([-0.1188,  1.6346, -1.9411])

In [22]:
c[1,3,:]

tensor([-1.1122,  2.1532,  1.0844])

In [23]:
torch.sum(a[1,:,:]*(b[3,:].unsqueeze(0)), dim=-1)

tensor([-1.1122,  2.1532,  1.0844])

In [1]:
import torch
B=2
T=3
L=4
C=5
a=torch.randn((B, L, T),dtype = torch.float32)
b=torch.randn((B, T, C), dtype = torch.float32)
c = torch.einsum('blt,btc->blc', a, b)

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
c[0,0,:]

tensor([ 1.6480, -3.5557, -1.7096, -2.2364,  1.8693])

In [3]:
torch.sum((a[0,0,:].unsqueeze(-1))*(b[0,:,:]),dim=0)

tensor([ 1.6480, -3.5557, -1.7096, -2.2364,  1.8693])

In [4]:
c[1,3,:]

tensor([-1.6070,  0.8835, -0.4102,  0.0650,  0.4597])

In [7]:
torch.sum((a[1,3,:].unsqueeze(-1))*(b[1,:,:]),dim=0)

tensor([-1.6070,  0.8835, -0.4102,  0.0650,  0.4597])

In [8]:
aa = torch.randn((B,T,C),dtype = torch.float32)
bb = torch.randn((L,C), dtype = torch.float32)
cc = torch.einsum('btc,lc->blt', aa, bb)

In [9]:
cc[0,0,:]

tensor([ 2.3396, -5.0251,  0.8336])

In [11]:
torch.sum(aa[0,:,:]*(bb[0,:].unsqueeze(0)),dim=1)

tensor([ 2.3396, -5.0251,  0.8336])

In [1]:
import torch

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
aaa = torch.randn((B, L, C), dtype=torch.float32)
bbb = torch.randn((L,C), dtype = torch.float32)
ccc = torch.einsum('blc,lc->bl', aaa, bbb)

NameError: name 'B' is not defined

In [13]:
ccc[0]

tensor([-3.4428, -0.4334,  0.6101, -1.4900])

In [14]:
torch.sum(aaa[0]*bbb, dim=-1)

tensor([-3.4428, -0.4334,  0.6101, -1.4900])

In [1]:
import torch
B = 2
T = 4
C = 5
a = torch.randn((B, T, C), dtype = torch.float32)
b = torch.randn((B, C), dtype = torch.float32)

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
a = a.transpose(-2, -1)
b = b.unsqueeze(1)

In [3]:
(b@a).shape

torch.Size([2, 1, 4])

In [3]:
import torch
A = torch.tensor(
    [[[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]],
     
     [[13, 14, 15, 16],
      [17, 18, 19, 20],
      [21, 22, 23, 24]]], dtype = torch.float32
)
B = torch.tensor(
    [[0.1, 0.2, 0.3, 0.4],
     [0.5, 0.6, 0.7, 0.8],
     [0.9, 1.0, 1.1, 1.2]], dtype = torch.float32
)

In [4]:
A.shape

torch.Size([2, 3, 4])

In [5]:
B.shape

torch.Size([3, 4])

In [6]:
torch.einsum('blc,lc->bl', A, B)

tensor([[ 3.0000, 17.4000, 44.6000],
        [15.0000, 48.6000, 95.0000]])

In [3]:
import torch
a = torch.tensor([1, 2, 3, 4], dtype = torch.float32)
b = torch.tensor([[11,11,11],[22,22,22],[33,33,33], [25,25,25]], dtype = torch.float32)

In [4]:
a.unsqueeze(-1) * b

tensor([[ 11.,  11.,  11.],
        [ 44.,  44.,  44.],
        [ 99.,  99.,  99.],
        [100., 100., 100.]])

In [5]:
c = torch.tensor([0.1,0.2,0.3])
b @ c.t()

tensor([ 6.6000, 13.2000, 19.8000, 15.0000])

In [1]:
import torch
import torch.nn.functional as F
v = torch.randn((10, 50), dtype = torch.float32)

In [2]:
norm_v = F.normalize(v, dim=-1)

In [3]:
norm_v.shape

torch.Size([10, 50])

In [5]:
torch.sum(norm_v[0]**2)

tensor(1.0000)

In [16]:
weight = F.softmax(torch.randn(10, dtype = torch.float32), dim=-1)

In [17]:
weight

tensor([0.0559, 0.0668, 0.0325, 0.0634, 0.1302, 0.1256, 0.4485, 0.0182, 0.0051,
        0.0538])

In [18]:
torch.sum(weight)

tensor(1.)

In [19]:
weight.shape

torch.Size([10])

In [22]:
weighted_v = weight.unsqueeze(-1)* norm_v

In [23]:
torch.sum(
    torch.sum(weighted_v, dim=0)**2
)

tensor(0.2492)

In [32]:
import math
(0.9* math.sqrt(2)/2+0.1*1)**2 + (0.9* math.sqrt(2)/2)**2

0.9472792206135787

In [3]:
[[False ]*5 for _ in range(4)]

[[False, False, False, False, False],
 [False, False, False, False, False],
 [False, False, False, False, False],
 [False, False, False, False, False]]

In [4]:
dire = [[-1, 0], [1, 0], [0, -1], [0, 1]]
for x,y in dire:
    print(x,y)

-1 0
1 0
0 -1
0 1


In [5]:
list(i+1 for i in range(4))

[1, 2, 3, 4]

In [1]:
import torch
a = torch.randn((2, 3), dtype = torch.float32)
torch.zeros(a.shape)

/home/yl/anaconda3/envs/py38/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
a = [[1,2],[1,3],[2,2],[3,3]]
a.sort(key=lambda t: (t[1], t[0]), reverse=True)

In [9]:
a

[[3, 3], [1, 3], [2, 2], [1, 2]]

In [10]:
a = [0,1,0,2]

In [12]:
sum([x==0 for x in a])

2

In [5]:
0>>1

0

In [6]:
a = [1,2,3]

In [7]:
a[0]>>1

0

In [9]:
a[0] = a[0]>>1

In [10]:
a

[0, 2, 3]

In [11]:
sum(a)

5

In [12]:
[0]*4

[0, 0, 0, 0]

In [6]:
s = '1011'
a = [1 if i=='1' else -1 for i in s]

In [7]:
a

[1, -1, 1, 1]

In [9]:
a = ['1', '2', '3']
list(map(int, a))

[1, 2, 3]

In [12]:
pow(1296, 1/2) == 36

True

In [13]:
pow(36, 2)

1296

In [14]:
path = ['12']

In [16]:
path + ['9']

['12', '9']

In [6]:
[float('inf')]*3

[inf, inf, inf]

In [9]:
[[0]*4 for _ in range(4)] 

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [10]:
pow(10, 9)

1000000000

In [11]:
float('inf') == float('inf')

True

In [2]:
'011'<'110'

True

In [6]:
a = ['011', '01']
list(map(int, a))

[11, 1]

In [7]:
min('011', '101')

'011'

In [11]:
a = [1, 3]

In [12]:
b = [i for _ in range(4) for i in a]

In [14]:
b

[1, 3, 1, 3, 1, 3, 1, 3]

In [1]:
a = [1,2,2,1,3]

In [2]:
from collections import Counter
b = Counter(a)

In [12]:
4 in b.keys()

False

In [14]:
d = {}
d.update({1:3})

In [15]:
d

{1: 3}

In [16]:
d.update({2:4})

In [17]:
d

{1: 3, 2: 4}

In [18]:
d[1]

3

In [22]:
list(b.keys()).sort()

In [46]:
125|68, 125&68

(125, 68)

In [47]:
bin(125)

'0b1111101'

In [48]:
bin(85)

'0b1010101'

In [49]:
bin(68)

'0b1000100'

In [50]:
41|84, 41&84

(125, 0)

In [51]:
int(0b111)

7

In [53]:
bin(73),bin(37),bin(41),bin(84)

('0b1001001', '0b100101', '0b101001', '0b1010100')

In [57]:
int(0b1101101)

109

In [58]:
73|37, 73&37

(109, 1)

In [59]:
bin(41)

'0b101001'

In [63]:
109|84

125

In [64]:
109&84

68

In [66]:
41&68

0

In [9]:
class Solution:
    def __init__(self, n):
        self.root = [i for i in range(n)]

    def add(self, idx1, idx2):
        # 找到idx1和idx2的根节点
        root1 = self.find(idx1)
        root2 = self.find(idx2)
        # idx2的根节点为idx1
        self.root[root2] = root1

    def find(self, idx):
        if self.root[idx] == idx:
            return idx
        else:
            return self.find(self.root[idx])
            

In [10]:
sol = Solution(n=4)

In [11]:
sol.root

[0, 1, 2, 3]

In [12]:
sol.add(0, 1)

In [13]:
sol.root

[0, 0, 2, 3]

In [14]:
sol.add(2, 1)

In [15]:
sol.root

[2, 0, 2, 3]

In [1]:
a = [[1, 2, 3], [4, 5, 6]]

In [3]:
b= []

for i in a:
    b += i 

In [4]:
b

[1, 2, 3, 4, 5, 6]

In [14]:
1^1

0

In [15]:
3^4

7

In [6]:
a = [2, 1, 3, 3]
sorted(range(len(a)), key=lambda x: a[x])

[1, 0, 2, 3]

In [7]:
b = a[::-1]

In [8]:
b

[3, 3, 1, 2]

In [9]:
a = [[1,1]]

In [11]:
a[0][1]

1

In [16]:
a = [2, 1, 3]
b = [1, 2]
c = sorted(b, key = lambda x: a[x], reverse=True)

In [18]:
b.sort(reverse=True, key = lambda x: a[x])

In [19]:
b

[2, 1]

In [20]:
a = [1,2,3]

In [21]:
a.reverse()

In [22]:
a

[3, 2, 1]

In [1]:
time = [[1,1,2,1],[1,1,3,1],[1,1,4,1]]

In [4]:
time.sort(key = lambda x: x[0]+x[2])

In [5]:
time

[[1, 1, 2, 1], [1, 1, 3, 1], [1, 1, 4, 1]]

In [6]:
sorted(range(len(time)), key = lambda x: time[x][2])

[0, 1, 2]

In [5]:
num = 10
count = 0
while num:
    if num & 1:
        count += 1
    num = num >>1

In [13]:
x = 10
count = int.bit_length(x)
print(count)

4


In [14]:
ans = 1>0

In [15]:
ans

True

In [16]:
ans += 1

In [17]:
ans

2

In [22]:
int(pow(8, 1/2))

2

In [1]:
-1%5

4

In [3]:
from collections import deque
a = deque()

In [4]:
a

deque([])

In [6]:
a

deque([1])

In [7]:
a.popleft()

1

In [8]:
a

deque([])

In [9]:
len(a)

0

In [10]:
def f(nums):
    n = len(nums)
    queue = deque()
    for i in range(n):
        if not queue:
            queue.append(i)
        # i和栈顶的元素比较
        if nums[i]> nums[queue[0]]:
            queue.popleft()
        else:
            queue.append(i)
    return len(queue)

In [11]:
nums = [1,3,4,9]
f(nums)

2

In [1]:
a = 'xyz'

In [2]:
a.replace('x', 'aa')

'aayz'

In [3]:
a.replace('y', '\'')

"x'z"

In [4]:
a = [1,2,1,1,]

In [5]:
from collections import Counter

In [11]:
Counter(a).most_common()

[(1, 3), (2, 1)]

In [17]:
a = [1, 2, 3, 4]

In [18]:
a

[1, 2, 3, 4]

In [19]:
a[:2:-1]

[4]

In [24]:
a = []

In [25]:
a + [1]

[1]

In [26]:
a = ()

In [32]:
a+(1,)+(2,)

(1, 2)

In [3]:
nums = [3,2,4]
mod = [True if nums[i]%2==1 else False for i in range(3)]

In [4]:
mod

[True, False, False]

In [5]:
a = [0, 1, 2]

In [8]:
a[:3]

[0, 1, 2]

In [9]:
from collections import Counter

In [10]:
a = Counter([0])

In [13]:
a.update({1:1})

In [14]:
a

Counter({0: 1, 1: 2})

In [18]:
nums = [0,1,2,3,4,5,6]

In [19]:
nums

[0, 1, 2, 3, 4, 5, 6]

In [20]:
nums[:2], nums[2:] = nums[-2:][::-1], nums[:-2]

In [21]:
nums

[6, 5, 0, 1, 2, 3, 4]

In [1]:
from collections import Counter

In [2]:
a = Counter(
)

In [6]:
a.update({0:1})

In [7]:
a

Counter({0: 2})

In [8]:
a[0]

2

In [9]:
0 in a

True

In [10]:
a = {1:[1]}

In [11]:
a[1].append(3)

In [12]:
a

{1: [1, 3]}

In [13]:
nums = [4,52,38,59,71,27,31,83,88,10]
label = sorted([[num, i] for i, num in enumerate(nums)], key = lambda x: x[0])

In [14]:
label

[[4, 0],
 [10, 9],
 [27, 5],
 [31, 6],
 [38, 2],
 [52, 1],
 [59, 3],
 [71, 4],
 [83, 7],
 [88, 8]]

In [15]:
a = [6, 5, 4, 3, 2]

In [17]:
a[[1, 2, 3]]

TypeError: list indices must be integers or slices, not list

In [4]:
d = 1
while True:
    if d*d %(4*5) == 0:
        k = d
        break
    d+=1

In [5]:
k

10

In [7]:
from collections import Counter

In [8]:
a = Counter()

In [9]:
a[(1, 0)]

0

In [11]:
a = dict()

In [12]:
a[(1, 0)] = 1

In [13]:
a

{(1, 0): 1}

In [1]:
from collections import deque

In [14]:
a = deque()

In [15]:
a.append(1)

In [16]:
a.append(2)

In [17]:
a

deque([1, 2])

In [18]:
a.insert(1, 22)

In [19]:
a

deque([1, 22, 2])

In [20]:
a

deque([1, 22, 2])

In [22]:
a = a[0:1]+a[3:4]

TypeError: sequence index must be integer, not 'slice'

In [23]:
a

deque([1, 22, 2])

In [25]:
a[0:1]

TypeError: sequence index must be integer, not 'slice'

In [26]:
a = set()

In [27]:
a.add(1)

In [33]:
a.add(2)

In [1]:
high = 100

In [2]:
str(1).zfill(3)

'001'

In [4]:
ord('z')-ord('a')

25

In [6]:
[1,2, 2, 3] == [1,2, 2, 3]

True

In [7]:
3*'A'

'AAA'

In [4]:
from collections import Counter
a = Counter([1,1,2, 3, 4,4])

In [5]:
a.items()

dict_items([(1, 2), (2, 1), (3, 1), (4, 2)])

In [6]:
d = {}

In [7]:
d.append('s')

AttributeError: 'dict' object has no attribute 'append'

In [8]:
a = 'asd'

In [10]:
a[:3]

'asd'

In [2]:
[[0,0] for _ in range(5)]

[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

In [3]:
s='abc'

In [4]:
s[::-1]

'cba'

In [6]:
[['']*4 for _ in range(4)]

[['', '', '', ''], ['', '', '', ''], ['', '', '', ''], ['', '', '', '']]

In [1]:
a = [[0,1,2],[0, 1, 1], [0, 1, 3]]

In [6]:
a.sort(key = lambda x: [x[1], x[2]])

In [7]:
a

[[0, 1, 1], [0, 1, 2], [0, 1, 3]]

In [12]:
35^32

3

In [13]:
3^1

2

In [22]:
from collections import Counter
nums = [1,32,1,2]
nums = Counter(nums)

In [23]:
nums

Counter({1: 2, 32: 1, 2: 1})

In [3]:
a = 1
a.bit_length()

1

In [14]:
a = {}

In [15]:
a.update({1:{}})

In [16]:
a

{1: {}}

In [12]:
a[1][1] = []

In [13]:
a

{1: {1: []}}

In [17]:
list(range(1))

[0]

In [18]:
a = {1:[1,2], 2:[1, 3]}
for _ , l in a.items():
    print(l)

[1, 2]
[1, 3]


In [1]:
a = [1, 2, 3]

In [5]:
int(''.join(str(s) for s in a))

123

In [6]:
from collections import Counter

In [9]:
for k, v in Counter(a).items():
    print(k, v)

1 1
2 1
3 1


In [4]:
def f(s: str) -> str:
    n = len(s)
    for i in range(n // 2):
        if ord(s[n-1-i]) > ord(s[i]):
            s[n-1-i] = s[i]
        else:
            s[i] = s[n-1-i]
    return s

In [5]:
s = 'abcd'

In [1]:
6&(-6)

2

In [2]:
a = 15

In [3]:
a.bit_length()

4

In [2]:
[[ ] for _ in range(4)]

[[], [], [], []]

In [6]:
77.85+79.76-76.70

80.91000000000001

In [1]:
a = [1, 1+1, 2, 3+4]

In [2]:
a

[1, 2, 2, 7]

In [4]:
-1//4

-1

In [7]:
[[] for _ in range(4)]

[[], [], [], []]

In [8]:
a = [1,2,3,4]

In [9]:
a.remove(2)

In [10]:
a

[1, 3, 4]